// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package get.me.a.tiramisu.entity;

import get.me.a.tiramisu.entity.Commentaire;
import javax.persistence.Entity;

privileged aspect Commentaire_Roo_Jpa_Entity {
    
    declare @type: Commentaire: @Entity;
    
}
