// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package get.me.a.tiramisu.dto;

import get.me.a.tiramisu.dto.RechercheTiramisuDTO;

privileged aspect RechercheTiramisuDTO_Roo_JavaBean {
    
    public void RechercheTiramisuDTO.setPrix(float prix) {
        this.prix = prix;
    }
    
}
